language: go
install:
 - go get github.com/njcx/gopacket_dpdk
 - go get github.com/njcx/gopacket_dpdk/layers
 - go get github.com/njcx/gopacket_dpdk/tcpassembly
script:
 - go test github.com/njcx/gopacket_dpdk
 - go test github.com/njcx/gopacket_dpdk/layers
 - go test github.com/njcx/gopacket_dpdk/tcpassembly
 - ./.travis.gofmt.sh
 #- ./.travis.govet.sh
